// Mock data for demo when backend is not available
export const mockProperties = [
  {
    id: '1',
    title: 'Moderno Departamento en Miraflores',
    address: 'Av. Larco 500, Miraflores, Lima',
    district: 'Miraflores',
    status: 'Entrega inmediata',
    price_soles: 450000,
    price_usd: 120000,
    bedrooms: '3 dorm.',
    bathrooms: 2,
    area_range_m2: '95 m²',
    amenities: '["Gimnasio", "Piscina", "Área de juegos", "Seguridad 24h"]',
    photo: null,
    latitude: -12.1191,
    longitude: -77.0289,
  },
  {
    id: '2',
    title: 'Exclusivo Flat en San Isidro',
    address: 'Calle Las Flores 200, San Isidro, Lima',
    district: 'San Isidro',
    status: 'En construcción',
    price_soles: 680000,
    price_usd: 181333,
    bedrooms: '2 dorm.',
    bathrooms: 2,
    area_range_m2: '120 m²',
    amenities: '["Gimnasio", "Rooftop", "Coworking", "Lobby"]',
    photo: null,
    latitude: -12.0977,
    longitude: -77.0365,
  },
  {
    id: '3',
    title: 'Acogedor Departamento en Barranco',
    address: 'Jr. San Martín 150, Barranco, Lima',
    district: 'Barranco',
    status: 'Entrega inmediata',
    price_soles: 320000,
    price_usd: 85333,
    bedrooms: '2 dorm.',
    bathrooms: 1,
    area_range_m2: '75 m²',
    amenities: '["Terraza", "Vista al mar", "Áreas verdes"]',
    photo: null,
    latitude: -12.1447,
    longitude: -77.0214,
  },
  {
    id: '4',
    title: 'Amplio Departamento Familiar en Surco',
    address: 'Av. El Polo 800, Santiago de Surco, Lima',
    district: 'Santiago de Surco',
    status: 'En planos · Entrega 2026',
    price_soles: 520000,
    price_usd: 138667,
    bedrooms: '4 dorm.',
    bathrooms: 3,
    area_range_m2: '150 m²',
    amenities: '["Gimnasio", "Piscina", "Salón de niños", "Parrilla"]',
    photo: null,
    latitude: -12.1333,
    longitude: -76.9833,
  },
  {
    id: '5',
    title: 'Nuevo Proyecto en La Molina',
    address: 'Av. La Fontana 300, La Molina, Lima',
    district: 'La Molina',
    status: 'En planos · Entrega 2027',
    price_soles: 380000,
    price_usd: 101333,
    bedrooms: '3 dorm.',
    bathrooms: 2,
    area_range_m2: '110 m²',
    amenities: '["Áreas verdes", "Seguridad 24h", "Estacionamiento"]',
    photo: null,
    latitude: -12.0833,
    longitude: -76.9333,
  },
  {
    id: '6',
    title: 'Departamento de Estreno en San Borja',
    address: 'Av. San Borja Norte 500, San Borja, Lima',
    district: 'San Borja',
    status: 'Entrega inmediata',
    price_soles: 410000,
    price_usd: 109333,
    bedrooms: '2 dorm.',
    bathrooms: 2,
    area_range_m2: '85 m²',
    amenities: '["Gimnasio", "Sauna", "Ascensor"]',
    photo: null,
    latitude: -12.1067,
    longitude: -77.0000,
  },
  {
    id: '7',
    title: 'Confortable Suite en Lince',
    address: 'Av. Arequipa 2500, Lince, Lima',
    district: 'Lince',
    status: 'Entrega inmediata',
    price_soles: 195000,
    price_usd: 52000,
    bedrooms: '1 dorm.',
    bathrooms: 1,
    area_range_m2: '45 m²',
    amenities: '["Ascensor", "Seguridad 24h"]',
    photo: null,
    latitude: -12.0833,
    longitude: -77.0333,
  },
  {
    id: '8',
    title: 'Elegante Penthouse en Miraflores',
    address: 'Malecón Cisneros 1200, Miraflores, Lima',
    district: 'Miraflores',
    status: 'Entrega inmediata',
    price_soles: 1200000,
    price_usd: 320000,
    bedrooms: '4 dorm.',
    bathrooms: 4,
    area_range_m2: '250 m²',
    amenities: '["Vista al mar", "Terraza", "Jacuzzi", "Gimnasio privado"]',
    photo: null,
    latitude: -12.1220,
    longitude: -77.0350,
  },
  {
    id: '9',
    title: 'Departamento Económico en Breña',
    address: 'Av. Bolivia 400, Breña, Lima',
    district: 'Breña',
    status: 'En planos · Entrega 2025',
    price_soles: 175000,
    price_usd: 46667,
    bedrooms: '2 dorm.',
    bathrooms: 1,
    area_range_m2: '55 m²',
    amenities: '["Área de juegos", "Parrilla"]',
    photo: null,
    latitude: -12.0583,
    longitude: -77.0500,
  },
  {
    id: '10',
    title: 'Moderno Flat en Jesús María',
    address: 'Av. Brasil 1800, Jesús María, Lima',
    district: 'Jesús María',
    status: 'Entrega inmediata',
    price_soles: 285000,
    price_usd: 76000,
    bedrooms: '2 dorm.',
    bathrooms: 1,
    area_range_m2: '70 m²',
    amenities: '["Gimnasio", "Lobby", "Ascensor"]',
    photo: null,
    latitude: -12.0708,
    longitude: -77.0458,
  },
  {
    id: '11',
    title: 'Departamento Vista al Mar en Chorrillos',
    address: 'Malecón Grau 500, Chorrillos, Lima',
    district: 'Chorrillos',
    status: 'En construcción',
    price_soles: 340000,
    price_usd: 90667,
    bedrooms: '3 dorm.',
    bathrooms: 2,
    area_range_m2: '100 m²',
    amenities: '["Vista al mar", "Piscina", "Gimnasio"]',
    photo: null,
    latitude: -12.1667,
    longitude: -77.0167,
  },
  {
    id: '12',
    title: 'Lujoso Departamento en San Isidro Golf',
    address: 'Calle Los Eucaliptos 300, San Isidro, Lima',
    district: 'San Isidro',
    status: 'Entrega inmediata',
    price_soles: 950000,
    price_usd: 253333,
    bedrooms: '3 dorm.',
    bathrooms: 3,
    area_range_m2: '180 m²',
    amenities: '["Vista al golf", "Gimnasio", "Spa", "Concierge"]',
    photo: null,
    latitude: -12.1000,
    longitude: -77.0400,
  },
]

export function filterProperties(properties, filters) {
  return properties.filter((p) => {
    if (filters.search) {
      const search = filters.search.toLowerCase()
      if (!p.title.toLowerCase().includes(search) && !p.address.toLowerCase().includes(search)) {
        return false
      }
    }
    if (filters.district && p.district !== filters.district) {
      return false
    }
    if (filters.bedrooms) {
      const beds = filters.bedrooms === '4+' ? 4 : parseInt(filters.bedrooms)
      const propBeds = parseInt(p.bedrooms) || 0
      if (filters.bedrooms === '4+' ? propBeds < 4 : propBeds !== beds) {
        return false
      }
    }
    if (filters.priceRange) {
      const [min, max] = filters.priceRange.split('-').map(Number)
      if (min && p.price_soles < min) return false
      if (max && p.price_soles > max) return false
    }
    return true
  })
}
